# -*- coding: utf-8 -*-

from sklearn.neighbors import KNeighborsClassifier as KNN
import pandas as pd
import random
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import math


class Ui_Form(object):
    def Gemi_Kapasite(self):
        
        max_konteyner=self.maxteutxt.text()
        max_agirlik=self.maxagirliktxt.text()
        max_yukseklik=self.maxyukseklik.text()
        max_genislik=self.lineEdit.text()
        kapak1_txt=self.kapak1.text()
        kapak2_txt=self.kapak1_2.text()
        kapak3_txt=self.kapak1_3.text()
        kapak4_txt=self.kapak1_4.text()
        kapak5_txt=self.kapak1_6.text()
        kapak6_txt=self.kapak1_5.text()
        
        if(max_konteyner!="" and max_agirlik!="" and max_yukseklik!="" and max_genislik!="" and kapak1_txt!="" and kapak2_txt!="" and kapak3_txt!="" and kapak4_txt!="" and kapak5_txt!="" and kapak6_txt!="" ):
            self.shipinfo_csv.append([max_konteyner,max_agirlik,max_yukseklik,max_genislik,kapak1_txt,kapak2_txt,kapak3_txt,kapak4_txt,kapak5_txt,kapak6_txt])
            
            self.gemitplm_label.setText(max_konteyner)
            self.ambar1_tplm.setText(kapak1_txt)
            self.ambar2_tplm.setText(kapak2_txt)
            self.ambar3_tplm.setText(kapak3_txt)
            self.ambar4_tplm.setText(kapak4_txt)
            self.ambar5_tplm.setText(kapak5_txt)
            self.ambar6_tplm.setText(kapak6_txt)
            
            self.maxteutxt.setText('')
            self.maxagirliktxt.setText('')
            self.maxyukseklik.setText('')
            self.lineEdit.setText('')
            self.kapak1.setText('')
            self.kapak1_2.setText('')
            self.kapak1_3.setText('')
            self.kapak1_4.setText('')
            self.kapak1_5.setText('')
            self.kapak1_6.setText('')

            
            self.msg = QMessageBox()
            self.msg.setIcon(QMessageBox.Information)
            self.msg.setText("Gemi Kapasite Değerleriniz Kaydedildi.")
            self.msg.setWindowTitle("Bilgi")
            self.msg.show()
             
        else:
            self.msgWarning = QMessageBox()
            self.msgWarning.setIcon(QMessageBox.Warning)
            self.msgWarning.setText("Lütfen Tüm Alanları <b>Doldurunuz</b>.")
            self.msgWarning.setWindowTitle("Uyarı")
            self.msgWarning.show()
        
            
        
        
    def Konteyner_Kod(self,x,y,z):
        randomAlfabe1 = chr(random.randint(ord('A'), ord('Z')))
        randomAlfabe2 = chr(random.randint(ord('A'), ord('Z')))
        randomAlfabe3 = chr(random.randint(ord('A'), ord('Z')))
        bay_number=x
        vertical_number=z
        horizontal_number=y
        
        kntyr_kd=randomAlfabe1+randomAlfabe2+randomAlfabe3+str(bay_number)+str(vertical_number)+str(horizontal_number)
        
        return(kntyr_kd)   
    
    
    def Plan_Olustur(self):
        print("plandayım")
        numrowss = len(self.plan_yukler)  
        numcolss = len(self.plan_yukler[0])  
        
        self.tableWidget_2.setColumnCount(numcolss)
        self.tableWidget_2.setRowCount(numrowss)
        
        
        for row in range(numrowss):
            for column in range(numcolss):
                self.tableWidget_2.setItem(row, column,QtWidgets.QTableWidgetItem((self.plan_yukler[row][column])))
        
        self.msg = QMessageBox()
        self.msg.setIcon(QMessageBox.Information)
        self.msg.setText("Planınız Başarıyla Oluşturulmuştur.")
        self.msg.setWindowTitle("Bilgi")
        self.msg.show()
        
        
        
    def Yuk_Kaydet(self):
        kntynr_turu=self.comboBox.currentText()
        yklnck_port=self.comboBox_3.currentText()
        gdlck_port=self.comboBox_2.currentText()
        kntynr_weight=self.lineEdit_3.text()

        
        
        if(yklnck_port=="MERSINPORT"):
            strport=11
        elif(yklnck_port=="MARSEILLEPORT"):
            strport=10
        elif(yklnck_port=="ORANPORT"):
            strport=12
       
        if(gdlck_port=="MERSINPORT"):
            stpport=11
        elif(gdlck_port=="MARSEILLEPORT"):
            stpport=10
        elif(gdlck_port=="ORANPORT"):
            stpport=12
             
             
        find_container=[[int(strport),int(stpport),float(kntynr_weight)]]  
        konum=self.model.predict(find_container)
        
        bay_knm=konum[0][0]
        yty_knm=konum[0][1]
        dky_knm=konum[0][2]
        
        
        
        if([konum[0][0],konum[0][1],konum[0][2]] in self.yukler):
   
            x=konum[0][1]
            while True:
                yty_knm=random.randint(1,17)
                konum[0][1]=yty_knm
                if(x!=yty_knm):
                    if([konum[0][0],konum[0][1],konum[0][2]] not in self.yukler):
                        kodd=self.Konteyner_Kod(bay_knm,yty_knm,dky_knm)
                        
                        self.plan_yukler.append([str(kodd),yklnck_port,gdlck_port,kntynr_turu,str(kntynr_weight),str(konum[0][0]),str(konum[0][1]),str(konum[0][2])])
                        self.yukler.append([konum[0][0],konum[0][1],konum[0][2]])
                        
                        if(bay_knm==1):
                            self.ambar1_yklnn.setText(str(int(self.ambar1_yklnn.text())+int(1)))
                            self.ambar1_bar.setValue(math.ceil((int(self.ambar1_yklnn.text())*int(100))/int(self.ambar1_tplm.text())))
                        elif(bay_knm==2):
                            self.ambar2_yklnn.setText(str(int(self.ambar2_yklnn.text())+int(1)))
                            self.ambar2_bar.setValue(math.ceil((int(self.ambar2_yklnn.text())*int(100))/int(self.ambar2_tplm.text())))
                        elif(bay_knm==3):
                            self.ambar3_yklnn.setText(str(int(self.ambar3_yklnn.text())+int(1)))
                            self.ambar3_bar.setValue(math.ceil((int(self.ambar3_yklnn.text())*int(100))/int(self.ambar3_tplm.text())))
                        elif(bay_knm==4):
                            self.ambar4_yklnn.setText(str(int(self.ambar4_yklnn.text())+int(1)))
                            self.ambar4_bar.setValue(math.ceil((int(self.ambar4_yklnn.text())*int(100))/int(self.ambar4_tplm.text())))
                        elif(bay_knm==5):
                            self.ambar5_yklnn.setText(str(int(self.ambar5_yklnn.text())+int(1)))
                            self.ambar5_bar.setValue(math.ceil((int(self.ambar5_yklnn.text())*int(100))/int(self.ambar5_tplm.text())))
                        elif(bay_knm==6):
                            self.ambar6_yklnn.setText(str(int(self.ambar6_yklnn.text())+int(1)))
                            self.ambar6_bar.setValue(math.ceil((int(self.ambar6_yklnn.text())*int(100))/int(self.ambar6_tplm.text())))
                        break
        else:
            
            kodd=self.Konteyner_Kod(bay_knm,yty_knm,dky_knm)
            
            self.plan_yukler.append([str(kodd),yklnck_port,gdlck_port,kntynr_turu,kntynr_weight,str(konum[0][0]),str(konum[0][1]),str(konum[0][2])])
            self.yukler.append([konum[0][0],konum[0][1],konum[0][2]])
            if(bay_knm==1):
                self.ambar1_yklnn.setText(str(int(self.ambar1_yklnn.text())+int(1)))
                self.ambar1_bar.setValue(math.ceil((int(self.ambar1_yklnn.text())*int(100))/int(self.ambar1_tplm.text())))
            elif(bay_knm==2):
                self.ambar2_yklnn.setText(str(int(self.ambar2_yklnn.text())+int(1)))
                self.ambar2_bar.setValue(math.ceil((int(self.ambar2_yklnn.text())*int(100))/int(self.ambar2_tplm.text())))
            elif(bay_knm==3):
                self.ambar3_yklnn.setText(str(int(self.ambar3_yklnn.text())+int(1)))
                self.ambar3_bar.setValue(math.ceil((int(self.ambar3_yklnn.text())*int(100))/int(self.ambar3_tplm.text())))
            elif(bay_knm==4):
                self.ambar4_yklnn.setText(str(int(self.ambar4_yklnn.text())+int(1)))
                self.ambar4_bar.setValue(math.ceil((int(self.ambar4_yklnn.text())*int(100))/int(self.ambar4_tplm.text())))
            elif(bay_knm==5):
                self.ambar5_yklnn.setText(str(int(self.ambar5_yklnn.text())+int(1)))
                self.ambar5_bar.setValue(math.ceil((int(self.ambar5_yklnn.text())*int(100))/int(self.ambar5_tplm.text())))
            elif(bay_knm==6):
                self.ambar6_yklnn.setText(str(int(self.ambar6_yklnn.text())+int(1)))
                self.ambar6_bar.setValue(math.ceil((int(self.ambar6_yklnn.text())*int(100))/int(self.ambar6_tplm.text())))

        
       
        
        numRows=self.tableWidget.rowCount()
        self.tableWidget.insertRow(numRows)
        
        self.tableWidget.setItem(numRows,0,QtWidgets.QTableWidgetItem(str(kodd)))
        self.tableWidget.setItem(numRows,1,QtWidgets.QTableWidgetItem(self.comboBox_3.currentText()))
        self.tableWidget.setItem(numRows,2,QtWidgets.QTableWidgetItem(self.comboBox_2.currentText()))
        self.tableWidget.setItem(numRows,3,QtWidgets.QTableWidgetItem(self.lineEdit_3.text()))
        self.tableWidget.setItem(numRows,4,QtWidgets.QTableWidgetItem(self.comboBox.currentText()))
        self.tableWidget.setItem(numRows,5,QtWidgets.QTableWidgetItem(self.textEdit.toPlainText()))
        
        
        self.gemiyklnn_label.setText(str(int(self.ambar1_yklnn.text())+int(self.ambar2_yklnn.text())+int(self.ambar3_yklnn.text())+int(self.ambar4_yklnn.text())+int(self.ambar5_yklnn.text())+int(self.ambar6_yklnn.text())))   
        self.gemidrmbar.setValue(math.ceil(((int(self.ambar1_yklnn.text())+int(self.ambar2_yklnn.text())+int(self.ambar3_yklnn.text())+int(self.ambar4_yklnn.text())+int(self.ambar5_yklnn.text())+int(self.ambar6_yklnn.text()))*int(100))/int(self.gemitplm_label.text())))
        
        

        
        
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(846, 609)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Gemi = QtWidgets.QWidget()
        self.tab_Gemi.setObjectName("tab_Gemi")
        self.label_6 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_6.setGeometry(QtCore.QRect(460, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_4.setGeometry(QtCore.QRect(80, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_9.setGeometry(QtCore.QRect(420, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.kapak1_5 = QtWidgets.QLineEdit(self.tab_Gemi)
        self.kapak1_5.setGeometry(QtCore.QRect(670, 120, 101, 20))
        self.kapak1_5.setText("")
        self.kapak1_5.setObjectName("kapak1_5")
        self.kapak1_6 = QtWidgets.QLineEdit(self.tab_Gemi)
        self.kapak1_6.setGeometry(QtCore.QRect(670, 90, 101, 20))
        self.kapak1_6.setText("")
        self.kapak1_6.setObjectName("kapak1_6")
        self.label = QtWidgets.QLabel(self.tab_Gemi)
        self.label.setGeometry(QtCore.QRect(10, 50, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_11.setGeometry(QtCore.QRect(600, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_8 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_8.setGeometry(QtCore.QRect(420, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.kapak1 = QtWidgets.QLineEdit(self.tab_Gemi)
        self.kapak1.setGeometry(QtCore.QRect(490, 60, 101, 20))
        self.kapak1.setObjectName("kapak1")
        self.label_3 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_3.setGeometry(QtCore.QRect(90, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.maxagirliktxt = QtWidgets.QLineEdit(self.tab_Gemi)
        self.maxagirliktxt.setGeometry(QtCore.QRect(220, 90, 151, 20))
        self.maxagirliktxt.setObjectName("maxagirliktxt")
        self.maxteutxt = QtWidgets.QLineEdit(self.tab_Gemi)
        self.maxteutxt.setEnabled(True)
        self.maxteutxt.setGeometry(QtCore.QRect(220, 60, 151, 20))
        self.maxteutxt.setObjectName("maxteutxt")
        self.kapak1_4 = QtWidgets.QLineEdit(self.tab_Gemi)
        self.kapak1_4.setGeometry(QtCore.QRect(670, 60, 101, 20))
        self.kapak1_4.setObjectName("kapak1_4")
        self.kapak1_2 = QtWidgets.QLineEdit(self.tab_Gemi)
        self.kapak1_2.setGeometry(QtCore.QRect(490, 90, 101, 20))
        self.kapak1_2.setText("")
        self.kapak1_2.setObjectName("kapak1_2")
        self.maxyukseklik = QtWidgets.QLineEdit(self.tab_Gemi)
        self.maxyukseklik.setGeometry(QtCore.QRect(220, 120, 151, 20))
        self.maxyukseklik.setObjectName("maxyukseklik")
        self.label_2 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_2.setGeometry(QtCore.QRect(80, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_5.setGeometry(QtCore.QRect(90, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_12.setGeometry(QtCore.QRect(600, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.grfkbtn = QtWidgets.QPushButton(self.tab_Gemi)
        self.grfkbtn.setGeometry(QtCore.QRect(340, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.grfkbtn.setFont(font)
        self.grfkbtn.setObjectName("grfkbtn")
        self.kapak1_3 = QtWidgets.QLineEdit(self.tab_Gemi)
        self.kapak1_3.setGeometry(QtCore.QRect(490, 120, 101, 20))
        self.kapak1_3.setText("")
        self.kapak1_3.setObjectName("kapak1_3")
        self.label_10 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_10.setGeometry(QtCore.QRect(600, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(self.tab_Gemi)
        self.label_7.setGeometry(QtCore.QRect(420, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.tab_Gemi)
        self.line.setGeometry(QtCore.QRect(390, 20, 20, 161))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_Gemi)
        self.lineEdit.setGeometry(QtCore.QRect(220, 150, 151, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox = QtWidgets.QGroupBox(self.tab_Gemi)
        self.groupBox.setGeometry(QtCore.QRect(150, 250, 541, 301))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(30, 80, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(10, 110, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(10, 140, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(10, 170, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(10, 200, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setGeometry(QtCore.QRect(10, 230, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(10, 260, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gemidrmbar = QtWidgets.QProgressBar(self.groupBox)
        self.gemidrmbar.setGeometry(QtCore.QRect(130, 80, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.gemidrmbar.setFont(font)
        self.gemidrmbar.setProperty("value", 0)
        self.gemidrmbar.setAlignment(QtCore.Qt.AlignCenter)
        self.gemidrmbar.setObjectName("gemidrmbar")
        self.gemiyklnn_label = QtWidgets.QLabel(self.groupBox)
        self.gemiyklnn_label.setGeometry(QtCore.QRect(310, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.gemiyklnn_label.setFont(font)
        self.gemiyklnn_label.setObjectName("gemiyklnn_label")
        self.gemitplm_label = QtWidgets.QLabel(self.groupBox)
        self.gemitplm_label.setGeometry(QtCore.QRect(410, 80, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        self.gemitplm_label.setFont(font)
        self.gemitplm_label.setObjectName("gemitplm_label")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(130, 60, 391, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(130, 100, 391, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setGeometry(QtCore.QRect(360, 80, 20, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(200, 40, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(380, 40, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.line_9 = QtWidgets.QFrame(self.groupBox)
        self.line_9.setGeometry(QtCore.QRect(130, 130, 391, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.groupBox)
        self.line_10.setGeometry(QtCore.QRect(360, 110, 20, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.ambar1_bar = QtWidgets.QProgressBar(self.groupBox)
        self.ambar1_bar.setGeometry(QtCore.QRect(130, 110, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ambar1_bar.setFont(font)
        self.ambar1_bar.setProperty("value", 0)
        self.ambar1_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.ambar1_bar.setObjectName("ambar1_bar")
        self.ambar1_tplm = QtWidgets.QLabel(self.groupBox)
        self.ambar1_tplm.setGeometry(QtCore.QRect(410, 110, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        self.ambar1_tplm.setFont(font)
        self.ambar1_tplm.setObjectName("ambar1_tplm")
        self.ambar1_yklnn = QtWidgets.QLabel(self.groupBox)
        self.ambar1_yklnn.setGeometry(QtCore.QRect(310, 110, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ambar1_yklnn.setFont(font)
        self.ambar1_yklnn.setObjectName("ambar1_yklnn")
        self.line_17 = QtWidgets.QFrame(self.groupBox)
        self.line_17.setGeometry(QtCore.QRect(130, 160, 391, 16))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.ambar2_bar = QtWidgets.QProgressBar(self.groupBox)
        self.ambar2_bar.setGeometry(QtCore.QRect(130, 140, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ambar2_bar.setFont(font)
        self.ambar2_bar.setProperty("value", 0)
        self.ambar2_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.ambar2_bar.setObjectName("ambar2_bar")
        self.line_18 = QtWidgets.QFrame(self.groupBox)
        self.line_18.setGeometry(QtCore.QRect(360, 140, 20, 21))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.ambar2_tplm = QtWidgets.QLabel(self.groupBox)
        self.ambar2_tplm.setGeometry(QtCore.QRect(410, 140, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        self.ambar2_tplm.setFont(font)
        self.ambar2_tplm.setObjectName("ambar2_tplm")
        self.ambar2_yklnn = QtWidgets.QLabel(self.groupBox)
        self.ambar2_yklnn.setGeometry(QtCore.QRect(310, 140, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ambar2_yklnn.setFont(font)
        self.ambar2_yklnn.setObjectName("ambar2_yklnn")
        self.line_19 = QtWidgets.QFrame(self.groupBox)
        self.line_19.setGeometry(QtCore.QRect(130, 190, 391, 16))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.groupBox)
        self.line_20.setGeometry(QtCore.QRect(360, 170, 20, 21))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.ambar3_yklnn = QtWidgets.QLabel(self.groupBox)
        self.ambar3_yklnn.setGeometry(QtCore.QRect(310, 170, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ambar3_yklnn.setFont(font)
        self.ambar3_yklnn.setObjectName("ambar3_yklnn")
        self.ambar3_bar = QtWidgets.QProgressBar(self.groupBox)
        self.ambar3_bar.setGeometry(QtCore.QRect(130, 170, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ambar3_bar.setFont(font)
        self.ambar3_bar.setProperty("value", 0)
        self.ambar3_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.ambar3_bar.setObjectName("ambar3_bar")
        self.ambar3_tplm = QtWidgets.QLabel(self.groupBox)
        self.ambar3_tplm.setGeometry(QtCore.QRect(410, 170, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        self.ambar3_tplm.setFont(font)
        self.ambar3_tplm.setObjectName("ambar3_tplm")
        self.line_30 = QtWidgets.QFrame(self.groupBox)
        self.line_30.setGeometry(QtCore.QRect(130, 220, 391, 16))
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.line_31 = QtWidgets.QFrame(self.groupBox)
        self.line_31.setGeometry(QtCore.QRect(360, 200, 20, 21))
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.ambar4_bar = QtWidgets.QProgressBar(self.groupBox)
        self.ambar4_bar.setGeometry(QtCore.QRect(130, 200, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ambar4_bar.setFont(font)
        self.ambar4_bar.setProperty("value", 0)
        self.ambar4_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.ambar4_bar.setObjectName("ambar4_bar")
        self.ambar4_yklnn = QtWidgets.QLabel(self.groupBox)
        self.ambar4_yklnn.setGeometry(QtCore.QRect(310, 200, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ambar4_yklnn.setFont(font)
        self.ambar4_yklnn.setObjectName("ambar4_yklnn")
        self.ambar4_tplm = QtWidgets.QLabel(self.groupBox)
        self.ambar4_tplm.setGeometry(QtCore.QRect(410, 200, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        self.ambar4_tplm.setFont(font)
        self.ambar4_tplm.setObjectName("ambar4_tplm")
        self.line_32 = QtWidgets.QFrame(self.groupBox)
        self.line_32.setGeometry(QtCore.QRect(130, 250, 391, 16))
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.line_33 = QtWidgets.QFrame(self.groupBox)
        self.line_33.setGeometry(QtCore.QRect(360, 230, 20, 21))
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.ambar5_bar = QtWidgets.QProgressBar(self.groupBox)
        self.ambar5_bar.setGeometry(QtCore.QRect(130, 230, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ambar5_bar.setFont(font)
        self.ambar5_bar.setProperty("value", 0)
        self.ambar5_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.ambar5_bar.setObjectName("ambar5_bar")
        self.ambar5_tplm = QtWidgets.QLabel(self.groupBox)
        self.ambar5_tplm.setGeometry(QtCore.QRect(410, 230, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        self.ambar5_tplm.setFont(font)
        self.ambar5_tplm.setObjectName("ambar5_tplm")
        self.ambar5_yklnn = QtWidgets.QLabel(self.groupBox)
        self.ambar5_yklnn.setGeometry(QtCore.QRect(310, 230, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ambar5_yklnn.setFont(font)
        self.ambar5_yklnn.setObjectName("ambar5_yklnn")
        self.line_34 = QtWidgets.QFrame(self.groupBox)
        self.line_34.setGeometry(QtCore.QRect(130, 280, 391, 16))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.line_35 = QtWidgets.QFrame(self.groupBox)
        self.line_35.setGeometry(QtCore.QRect(360, 260, 20, 21))
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.ambar6_tplm = QtWidgets.QLabel(self.groupBox)
        self.ambar6_tplm.setGeometry(QtCore.QRect(410, 260, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        self.ambar6_tplm.setFont(font)
        self.ambar6_tplm.setObjectName("ambar6_tplm")
        self.ambar6_bar = QtWidgets.QProgressBar(self.groupBox)
        self.ambar6_bar.setGeometry(QtCore.QRect(130, 260, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ambar6_bar.setFont(font)
        self.ambar6_bar.setProperty("value", 0)
        self.ambar6_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.ambar6_bar.setObjectName("ambar6_bar")
        self.ambar6_yklnn = QtWidgets.QLabel(self.groupBox)
        self.ambar6_yklnn.setGeometry(QtCore.QRect(310, 260, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ambar6_yklnn.setFont(font)
        self.ambar6_yklnn.setObjectName("ambar6_yklnn")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_Gemi, icon, "")
        self.tab_Konteyner = QtWidgets.QWidget()
        self.tab_Konteyner.setObjectName("tab_Konteyner")
        self.Yuk_Kaydet_Btn = QtWidgets.QPushButton(self.tab_Konteyner)
        self.Yuk_Kaydet_Btn.setGeometry(QtCore.QRect(350, 420, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Yuk_Kaydet_Btn.setFont(font)
        self.Yuk_Kaydet_Btn.setObjectName("Yuk_Kaydet_Btn")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_Konteyner)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 851, 251))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.textEdit = QtWidgets.QTextEdit(self.tab_Konteyner)
        self.textEdit.setGeometry(QtCore.QRect(610, 340, 181, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_13 = QtWidgets.QLabel(self.tab_Konteyner)
        self.label_13.setGeometry(QtCore.QRect(220, 270, 331, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_Konteyner)
        self.label_14.setGeometry(QtCore.QRect(660, 310, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_Konteyner)
        self.label_15.setGeometry(QtCore.QRect(290, 310, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.comboBox = QtWidgets.QComboBox(self.tab_Konteyner)
        self.comboBox.setGeometry(QtCore.QRect(0, 337, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_16 = QtWidgets.QLabel(self.tab_Konteyner)
        self.label_16.setGeometry(QtCore.QRect(0, 310, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_Konteyner)
        self.lineEdit_3.setGeometry(QtCore.QRect(450, 340, 131, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_Konteyner)
        self.comboBox_2.setGeometry(QtCore.QRect(290, 340, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_18 = QtWidgets.QLabel(self.tab_Konteyner)
        self.label_18.setGeometry(QtCore.QRect(450, 310, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.tab_Konteyner)
        self.label_17.setGeometry(QtCore.QRect(140, 310, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_Konteyner)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 340, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_Konteyner, icon1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 10, 1001, 381))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(360, 420, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        
        ########################################################
        
        #BUTONLAR
        self.Yuk_Kaydet_Btn.clicked.connect(self.Yuk_Kaydet)
        self.pushButton.clicked.connect(self.Plan_Olustur)
        self.grfkbtn.clicked.connect(self.Gemi_Kapasite)
        #
        self.shipinfo_csv=[]
        
        self.veri=pd.read_csv('veriseti.csv')
        self.veri['STARTPORT'].replace(['FR','MER','DZ'],[10,11,12],inplace=True)
        # FRANSA=10 MERSİN=11 CEZAYİR=12 
        self.veri['STOPPORT'].replace(['FR','MER','DZ'],[10,11,12],inplace=True)
        
        self.girdi=self.veri.iloc[:, [0,1,3]].values
        self.cikti=self.veri.iloc[:,[6,4,5]].values
        
        self.model=KNN(n_neighbors=2)
        self.model.fit(self.girdi,self.cikti)
        
        
        
        
        self.yukler=[]
        self.plan_yukler=[]
        
        
        ###########################################################        
        
        
        
        
        
        

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Konteyner Yükleme Planı Oluşturma Programı"))
        self.label_6.setText(_translate("Form", "  -AMBAR KAPASİTELERİ-"))
        self.label_4.setText(_translate("Form", "Maximum Yükseklik:"))
        self.label_9.setText(_translate("Form", "3.Ambar :"))
        self.label.setText(_translate("Form", "Maximum Taşıma Kapasiteisi:"))
        self.label_11.setText(_translate("Form", "4.Ambar :"))
        self.label_8.setText(_translate("Form", "2.Ambar :"))
        self.label_3.setText(_translate("Form", "Maximum Ağırlık:"))
        self.label_2.setText(_translate("Form", "  -MAXİMUM KAPASİTELER-"))
        self.label_5.setText(_translate("Form", "Maximum Genişlik:"))
        self.label_12.setText(_translate("Form", "6.Ambar :"))
        self.grfkbtn.setText(_translate("Form", " Kaydet"))
        self.label_10.setText(_translate("Form", "5.Ambar :"))
        self.label_7.setText(_translate("Form", "1.Ambar :"))
        self.groupBox.setTitle(_translate("Form", "Gemi Kapasite Durumu"))
        self.label_19.setText(_translate("Form", "Gemi Doluluk :"))
        self.label_20.setText(_translate("Form", "1.Ambar Doluluk :"))
        self.label_21.setText(_translate("Form", "2.Ambar Doluluk :"))
        self.label_25.setText(_translate("Form", "3.Ambar Doluluk :"))
        self.label_26.setText(_translate("Form", "4.Ambar Doluluk :"))
        self.label_32.setText(_translate("Form", "5.Ambar Doluluk :"))
        self.label_33.setText(_translate("Form", "6.Ambar Doluluk :"))
        self.gemidrmbar.setFormat(_translate("Form", "%p%"))
        self.gemiyklnn_label.setText(_translate("Form", "0"))
        self.gemitplm_label.setText(_translate("Form", "0"))
        self.label_22.setText(_translate("Form", "Yüklenen Konteyner "))
        self.label_24.setText(_translate("Form", "Toplam Konteyner "))
        self.ambar1_bar.setFormat(_translate("Form", "%p%"))
        self.ambar1_tplm.setText(_translate("Form", "0"))
        self.ambar1_yklnn.setText(_translate("Form", "0"))
        self.ambar2_bar.setFormat(_translate("Form", "%p%"))
        self.ambar2_tplm.setText(_translate("Form", "0"))
        self.ambar2_yklnn.setText(_translate("Form", "0"))
        self.ambar3_yklnn.setText(_translate("Form", "0"))
        self.ambar3_bar.setFormat(_translate("Form", "%p%"))
        self.ambar3_tplm.setText(_translate("Form", "0"))
        self.ambar4_bar.setFormat(_translate("Form", "%p%"))
        self.ambar4_yklnn.setText(_translate("Form", "0"))
        self.ambar4_tplm.setText(_translate("Form", "0"))
        self.ambar5_bar.setFormat(_translate("Form", "%p%"))
        self.ambar5_tplm.setText(_translate("Form", "0"))
        self.ambar5_yklnn.setText(_translate("Form", "0"))
        self.ambar6_tplm.setText(_translate("Form", "0"))
        self.ambar6_bar.setFormat(_translate("Form", "%p%"))
        self.ambar6_yklnn.setText(_translate("Form", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Gemi), _translate("Form", "Gemi Özellikleri"))
        self.Yuk_Kaydet_Btn.setText(_translate("Form", "Kaydet"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Kod"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Yüklenecek Liman"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Teslim Edilecek Liman"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Yükün Ağırlığı"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Konteyner Türü"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Açıklama"))
        self.label_13.setText(_translate("Form", "YÜKLENECEK KONTEYNER  BİLGİLERİ"))
        self.label_14.setText(_translate("Form", "Açıklama"))
        self.label_15.setText(_translate("Form", "Teslim Edilecek Liman"))
        self.comboBox.setItemText(0, _translate("Form", "20"))
        self.comboBox.setItemText(1, _translate("Form", "40"))
        self.label_16.setText(_translate("Form", "Konteyner Türü"))
        self.comboBox_2.setItemText(0, _translate("Form", "MERSINPORT"))
        self.comboBox_2.setItemText(1, _translate("Form", "MARSEILLEPORT"))
        self.comboBox_2.setItemText(2, _translate("Form", "ORANPORT"))
        self.label_18.setText(_translate("Form", "Konteyner Ağırlığı"))
        self.label_17.setText(_translate("Form", "Yüklenecek Liman"))
        self.comboBox_3.setItemText(0, _translate("Form", "MERSINPORT"))
        self.comboBox_3.setItemText(1, _translate("Form", "MARSEILLEPORT"))
        self.comboBox_3.setItemText(2, _translate("Form", "ORANPORT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Konteyner), _translate("Form", "Yüklenecek Konteyner "))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Konteyner Kod"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Yüklenecek Liman"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Teslim Limanı"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Konteyner Türü"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Yükün Ağırlığı"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Bay No"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Yatay Konum"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Dikey Konum"))
        self.pushButton.setText(_translate("Form", "Gemi Planını Oluştur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Yükleme Programı"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
